repo = "rustc_codegen_cranelift"
filter = ":~(history=\"keep-trivial-merges,no-splice\")[:rev(<=2bc05d45078dbee6495c008cbd5d1dc24edff53f:prefix=compiler/rustc_codegen_cranelift,<=aa1ae1a5adf6797e401b5c1d949107f8622f240e:SQUASH)]:/compiler/rustc_codegen_cranelift"
filter-version = 2
